### ISSUE TITLE
iptables rule order

### ISSUE THREAD

**Issue by tony1661** [apiban/apiban-client-go#2]
Hi Fred,

Based on your experience, would it be best to have the APIBAN rule on INPUT after a `state RELATED,ESTABLISHED` rule for efficiency?

Currently the go-client adds it to the top of the list. I'm wondering if I should modify that.

Thanks!

**Comment by fredposner** [comment]
Hi,

We have not seen any impact with the rules as current. It's been in this state for several years now. If there is any data that would demonstrate a performance impact, it surely could be investigated.
